increment counter using mutative increment operator
test fails due to deep-freeze
TypeError: Cannot assign to read only property '1' of object '[object Array]'